
# http://127.0.0.1:5000/tasks/5


### CADASTRAR UMA TAREFA
POST http://127.0.0.1:5000/tasks
Content-Type: application/json

{
    "title": "Dar comida para o gato",
    "description": "222222"
}

### LISTAR TODAS AS TAREFAS
GET http://127.0.0.1:5000/tasks

### CAPTURA APENAS UMA TASK
GET http://127.0.0.1:5000/tasks/4

### ATUALIZA UMA TASK
PUT http://127.0.0.1:5000/tasks/5
Content-Type: application/json
Accept-Charset: 

{
    "title":"Estudar Flask",
    "description":"estudar crud",
    "completed":"false"
}

### DELETA UMA TASK
DELETE http://127.0.0.1:5000/tasks/1
Content-Type: application/json

